// Responsabilidade: estado global da aplicação

export const st = {
  files: [],
  searchResults: null,
  activeId: null,
  activeTags: [],
  activeFolder: "",
  activeStatus: "",
  filter: "all",
  search: "",
  view: "edit",
  isDirty: false,
  splitRatio: 0.5,
  tagFilter: null,
  expandedFolders: new Set(),
  activePanel: "explorer",
  sidebarOpen: true,
  saveTimer: null,
  searchTimer: null,
  pendingDelete: null,
  renamingId: null,
  emptyFolders: new Set(),
  draggingFileId: null,
  creatingFolder: false,
  kanbanMode: false,
  kanbanColumns: null,
  addingKanbanCol: false,
};
